// platform/skills — 11 core skill manifests (v0.6.0 knowledge-centric model)
// Protocol knowledge lives in agents/knowledge/protocols/.
// On-demand skills are generated by harness-bootstrap from agents/knowledge/.

export const CORE_SKILL_NAMES = [
  "audit", "consensus-tools", "designer", "fde-analyst", "harness-bootstrap",
  "merge-worktree", "orchestrator", "planner", "status", "verify", "wb-parser",
] as const;

export type CoreSkillName = typeof CORE_SKILL_NAMES[number];

// On-demand protocols available in agents/knowledge/protocols/ for harness generation
export const ON_DEMAND_PROTOCOLS = [
  "btw", "commit-convention", "convergence-loop", "doc-sync", "export",
  "fixer", "gap-detector", "mcp-builder", "mermaid", "qa-strategist",
  "retrospect", "rollback", "rtm-scanner", "scout", "skill-authoring",
] as const;

export type OnDemandProtocol = typeof ON_DEMAND_PROTOCOLS[number];

/** @deprecated Use CORE_SKILL_NAMES — kept for backward compatibility */
export const SKILL_NAMES = [...CORE_SKILL_NAMES, ...ON_DEMAND_PROTOCOLS] as const;
export type SkillName = typeof SKILL_NAMES[number];
